# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_actor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='actor2',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Movie'),
        ),
    ]
