# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160124_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='real_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
