# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_actor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actor_movies', to='web.Actor'),
        ),
    ]
